name: Build & deploy NBA-Go app

on:
  push: 
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy NBA-Go app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      

      

#      - name: Build docker image
 #       uses: actions/build-push-action@v2
  #      with:
   #       context: .
    #      dockerfile: Dockerfile
     #     push: false
#
