name: Build & deploy NBA-Go app

on:
  push: 
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy NBA-Go app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@vd3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
